Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,6 +1,6 @@
-name: 'Clon'
+name: 'Clone Github Repo Action'
 
-description: "workflows."
+description: "Github Action to clone a public or private Github repository and access its content on others repositories' workflows."
 
 inputs:
   owner:
@@ -9,21 +9,66 @@ inputs:
   repository:
     description: 'Repository name'
     required: true
-    default: "BR_kernel_a02"
- branch:
-    description: 'Branch name'
-    required: true
-    default: "kernelku"
+  access-token:
+    description: 'PAT with repository scope (https://github.com/settings/tokens)'
+    required: false
+  depth:
+    description: 'Depth of the clone (default: full history)'
+    required: false
+    default: ""
+  branch:
+    description: 'Branch name (default: kernelku)'
+    required: false
+    default: "kernelku" 
+  submodule:
+    description: 'Clone with submodules'
+    required: false
+    default: "false" 
 
 runs:
   using: 'composite'
   steps:
     - name: Clone repository
       run: |
-        git clone --branch "${{ inputs.branch }}" https://github.com/${{ inputs.owner }}/${{ inputs.repository }}.git  --recursive
+        if [ -z "${{ inputs.access-token }}" ]; then
+          if [ -z "${{ inputs.depth }}" ]; then
+            if [ "${{ inputs.submodule }}" = "true" ]; then
+              git clone --branch "${{ inputs.branch }}" https://github.com/${{ inputs.owner }}/${{ inputs.repository }}.git  --recursive
+            else
+              git clone --branch "${{ inputs.branch }}" https://github.com/${{ inputs.owner }}/${{ inputs.repository }}.git
+            fi
+          else
+            if [ "${{ inputs.submodule }}" = "true" ]; then
+              git clone --branch "${{ inputs.branch }}" --depth="${{ inputs.depth }}" https://github.com/${{ inputs.owner }}/${{ inputs.repository }}.git  --recursive
+            else
+              git clone --branch "${{ inputs.branch }}" --depth="${{ inputs.depth }}" https://github.com/${{ inputs.owner }}/${{ inputs.repository }}.git
+            fi
+          fi
+        else
+          if [ -z "${{ inputs.depth }}" ]; then
+            if [ "${{ inputs.submodule }}" = "true" ]; then
+              git clone --branch "${{ inputs.branch }}" https://${{ inputs.access-token }}@github.com/${{ inputs.owner }}/${{ inputs.repository }}.git  --recursive
+            else
+              git clone --branch "${{ inputs.branch }}" https://${{ inputs.access-token }}@github.com/${{ inputs.owner }}/${{ inputs.repository }}.git
+            fi
+          else
+            if [ "${{ inputs.submodule }}" = "true" ]; then
+              git clone --branch "${{ inputs.branch }}" --depth="${{ inputs.depth }}" https://${{ inputs.access-token }}@github.com/${{ inputs.owner }}/${{ inputs.repository }}.git  --recursive
+            else
+              git clone --branch "${{ inputs.branch }}" --depth="${{ inputs.depth }}" https://${{ inputs.access-token }}@github.com/${{ inputs.owner }}/${{ inputs.repository }}.git
+            fi
+          fi
+        fi
+
+        if [ -d "${{ inputs.repository }}" ]; then
+          echo "Cloned ${{ inputs.repository }} repository successfully."
+          echo "Access the repository content using \"cd ${{ inputs.repository }}.\""
+        else
+          echo "Error: Couldn't clone ${{ inputs.repository }} repository. Check the inputs or the PAT scope."
+          exit 1
+        fi
       shell: bash
 
 branding:
   icon: 'download'
   color: 'blue'
-
